#!/usr/bin/env python3
"""Compile chamber definitions into MACRO-11 source.

Usage:
    chambers_gen.py src/res/chambers --out build/data_chambers.mac [--force]

Input: ch00.txt .. ch19.txt (see extract_res.py).  Output:

    CHAMBER_TAB: .WORD CH00,...,CH19
    CHnn: 64-byte header (ZX layout: +6 patch list ptr as a word,
          +8 spawn A, +0x0B border, +0x0E/0x10 exit thresholds,
          +0x12 exit table 9x3, +0x2D spawn B, +0x30 anim specs)
          followed by the RLE-encoded 32x22 map (0 = end,
          n<0x80 = repeat next byte n times, n|0x80 = n literals).
    PLnn: patch list (guard bytes bit7-set, 3-byte set entries), 0xFF end.
"""
import argparse
import re
import sys
from pathlib import Path


def rle_encode(cells):
    out = bytearray()
    i = 0
    n = len(cells)
    while i < n:
        run = 1
        while i + run < n and cells[i + run] == cells[i] and run < 0x7F:
            run += 1
        if run >= 3:
            out += bytes([run, cells[i]])
            i += run
            continue
        # gather literals until a run of >=3 starts
        j = i
        while j < n and j - i < 0x7F:
            r = 1
            while j + r < n and cells[j + r] == cells[j] and r < 3:
                r += 1
            if r >= 3:
                break
            j += r
        out += bytes([0x80 | (j - i)]) + bytes(cells[i:j])
        i = j
    out.append(0)
    return bytes(out)


def rle_decode(data):
    cells = bytearray()
    i = 0
    while True:
        c = data[i]
        i += 1
        if c == 0:
            break
        if c & 0x80:
            cells += data[i : i + (c & 0x7F)]
            i += c & 0x7F
        else:
            cells += bytes([data[i]]) * c
            i += 1
    return bytes(cells)


def parse_chamber(path):
    spawn_a = spawn_b = (0, 0, 0)
    border = 0
    col_thr = row_thr = (0, 0)
    exits = [(255, 0, 0)] * 9
    anims = [(0, 0, 0, 0)] * 4
    cells = bytearray()
    patches = []
    mode = None
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        parts = line.split()
        key = parts[0]
        if mode == "map" and re.fullmatch(r"[0-9a-f]{2}", key):
            cells += bytes(int(p, 16) for p in parts)
            continue
        if mode == "patches" and key in ("guard", "set"):
            if key == "guard":
                patches.append(("guard", int(parts[1], 16)))
            else:
                patches.append(("set", int(parts[1]), int(parts[2]), int(parts[3], 16)))
            continue
        mode = None
        if key == "spawn_a":
            spawn_a = (int(parts[1]), int(parts[2]), int(parts[3], 16))
        elif key == "spawn_b":
            spawn_b = (int(parts[1]), int(parts[2]), int(parts[3], 16))
        elif key == "border":
            border = int(parts[1])
        elif key == "col_thr":
            col_thr = (int(parts[1]), int(parts[2]))
        elif key == "row_thr":
            row_thr = (int(parts[1]), int(parts[2]))
        elif key == "exit":
            e = int(parts[1])
            if parts[2] == "death":
                exits[e] = (255, 0, 0)
            else:
                exits[e] = (int(parts[2]), int(parts[3]), int(parts[4]))
        elif key == "anim":
            anims[int(parts[1])] = tuple(int(x) for x in parts[2:6])
        elif key == "map":
            mode = "map"
        elif key == "patches":
            mode = "patches"
        else:
            sys.exit(f"error: {path.name}: unknown line {raw!r}")
    if len(cells) != 32 * 22:
        sys.exit(f"error: {path.name}: map has {len(cells)} cells")
    return dict(spawn_a=spawn_a, spawn_b=spawn_b, border=border,
                col_thr=col_thr, row_thr=row_thr, exits=exits, anims=anims,
                cells=bytes(cells), patches=patches)


def bytelines(prefix, data, per=16):
    return [f"\t.BYTE\t" + ",".join(f"{b:03o}" for b in data[i : i + per])
            for i in range(0, len(data), per)]


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    if args.out.exists() and not args.force:
        sys.exit(f"error: {args.out} exists (use --force)")

    out = ["; Generated by tools/chambers_gen.py from src/res/chambers/",
           "; -- do not edit; edit the .txt files and rebuild.", "",
           "CHAMBER_TAB:"]
    names = [f"CH{n:02d}" for n in range(20)]
    out.append("\t.WORD\t" + ",".join(names[:10]))
    out.append("\t.WORD\t" + ",".join(names[10:]))
    for n in range(20):
        ch = parse_chamber(args.input / f"ch{n:02d}.txt")
        rle = rle_encode(ch["cells"])
        assert rle_decode(rle) == ch["cells"], f"ch{n}: RLE round-trip failed"
        h = bytearray(0x40)
        h[0x08:0x0B] = bytes(ch["spawn_a"])
        h[0x0B] = ch["border"]
        h[0x0E], h[0x0F] = ch["col_thr"]
        h[0x10], h[0x11] = ch["row_thr"]
        for e, (c2, cc, rr) in enumerate(ch["exits"]):
            h[0x12 + e * 3 : 0x15 + e * 3] = bytes((c2, cc, rr))
        h[0x2D:0x30] = bytes(ch["spawn_b"])
        for i, a in enumerate(ch["anims"]):
            off = (0x30, 0x34, 0x38, 0x3C)[i]
            h[off : off + 4] = bytes(a)
        out.append("")
        out.append("\t.EVEN")
        out.append(f"CH{n:02d}:")
        out += bytelines("", h[0:6])            # +0..+5 unused on UKNC
        out.append(f"\t.WORD\tPL{n:02d}\t\t; +6 patch list")
        out += bytelines("", h[8:0x40])
        out += bytelines("", rle)
        out.append(f"PL{n:02d}:")
        pl = bytearray()
        for p in ch["patches"]:
            if p[0] == "guard":
                pl.append(p[1])
            else:
                pl += bytes((p[1], p[2], p[3]))
        pl.append(0xFF)
        out += bytelines("", pl)
    out.append("\t.EVEN")
    out.append("")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out))
    print(f"{args.out}: 20 chambers")


if __name__ == "__main__":
    main()
