#!/usr/bin/env python3
"""Compile the HUD cell sheets (logo, fist) into MACRO-11 source.

Usage:
    hud_gen.py src/res/hud --out build/data_hud.mac [--force]

Input: logo.txt (64 cells), fist.txt (24 cells): 8x8 '.'/'#' bitmaps.
Output: HUD_LOGO: / HUD_FIST: 8 bytes per cell, bit 0 = leftmost pixel.
"""
import argparse
import sys
from pathlib import Path


def parse_sheet(path):
    cells = []
    rows = None
    for raw in path.read_text().splitlines():
        line = raw.strip()
        is_row = len(line) == 8 and all(c in ".#" for c in line)
        if not line or (line.startswith("#") and not is_row):
            continue
        if line.startswith("cell "):
            rows = []
            cells.append(rows)
            continue
        if rows is not None and len(line) == 8 and all(c in ".#" for c in line):
            rows.append(sum(1 << i for i, c in enumerate(line) if c == "#"))
    for i, r in enumerate(cells):
        if len(r) != 8:
            sys.exit(f"error: {path.name} cell {i}: {len(r)} rows")
    return cells


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    if args.out.exists() and not args.force:
        sys.exit(f"error: {args.out} exists (use --force)")
    out = ["; Generated by tools/hud_gen.py from src/res/hud/",
           "; -- do not edit; edit the .txt files and rebuild.", ""]
    for label, fname in (("HUD_LOGO", "logo.txt"), ("HUD_FIST", "fist.txt")):
        cells = parse_sheet(args.input / fname)
        out.append(f"{label}:")
        for i, rows in enumerate(cells):
            out.append("\t.BYTE\t" + ",".join(f"{r:03o}" for r in rows)
                       + f"\t; cell {i:02x}")
        out.append("")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out))
    print(f"{args.out}: HUD sheets")


if __name__ == "__main__":
    main()
