#!/usr/bin/env python3
"""Compile the beeper music into MACRO-11 source for the PPU program.

Usage:
    music_gen.py orig/game48k.bin --out build/data_music.mac [--force]
                 [--scale S]

The ZX engine (see .claude/docs/re-notes.md): song = 0-terminated list
of phrase pointers; phrase = 0-terminated list of note pointers;
note = {tone_ptr, cycles, rest}; tone = 0-terminated list of
half-period words.  Half-period time on the ZX = (90 + 26*N) / 3.5e6 s;
rest time = 26*N / 3.5e6 s.

The PPU player's delay unit is DLYT ticks of its 6.25 MHz clock
(SOB-loop, see src/ppu.mac SND_HALF).  --scale = ZX delay units per
PPU delay unit (default tuned for UKNCBTL).

All pointers are emitted as offsets from PP_START (the PPU program is
position independent; the player adds the load base at run time).
"""
import argparse
import sys
from pathlib import Path

BASE = 0x4000
SONGS = {"TUNE": 0x935C, "DEATH": 0x933A, "PICKUP": 0x9346}


def rw(mem, a):
    return mem[a - BASE] | (mem[a - BASE + 1] << 8)


def walk(mem):
    """Collect songs -> phrases -> notes -> tones, keyed by ZX address."""
    songs, phrases, notes, tones = {}, {}, {}, {}
    for name, sa in SONGS.items():
        plist = []
        a = sa
        while True:
            p = rw(mem, a)
            a += 2
            if p == 0:
                break
            plist.append(p)
            if p in phrases:
                continue
            nlist = []
            q = p
            while True:
                np = rw(mem, q)
                q += 2
                if np == 0:
                    break
                nlist.append(np)
                if np in notes:
                    continue
                tone, cycles, rest = rw(mem, np), rw(mem, np + 2), rw(mem, np + 4)
                notes[np] = (tone, cycles, rest)
                if tone not in tones:
                    hp = []
                    t = tone
                    while rw(mem, t):
                        hp.append(rw(mem, t))
                        t += 2
                    tones[tone] = hp
            phrases[p] = nlist
        songs[name] = plist
    return songs, phrases, notes, tones


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--scale", type=float, default=5.8,
                    help="ZX 26T delay units per PPU delay unit")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    if args.out.exists() and not args.force:
        sys.exit(f"error: {args.out} exists (use --force)")
    mem = args.input.read_bytes()
    songs, phrases, notes, tones = walk(mem)

    def cvt(n):  # ZX delay count -> PPU delay count, at least 1
        return max(1, round(n / args.scale))

    out = ["; Generated by tools/music_gen.py from the original tune data.",
           "; -- do not edit; rebuild (see tools/music_gen.py --help).",
           "; All pointers are offsets from PP_START.", ""]
    for name, plist in songs.items():
        out.append(f"MU_{name}:")
        out.append("\t.WORD\t" + ",".join(f"MP_{p:04X}-PP_START" for p in plist)
                   + ",0")
    for p, nlist in phrases.items():
        out.append(f"MP_{p:04X}:")
        out.append("\t.WORD\t" + ",".join(f"MN_{n:04X}-PP_START" for n in nlist)
                   + ",0")
    for n, (tone, cycles, rest) in notes.items():
        out.append(f"MN_{n:04X}:\t.WORD\tMT_{tone:04X}-PP_START,"
                   f"{cycles}.,{cvt(rest)}.")
    for t, hp in tones.items():
        out.append(f"MT_{t:04X}:\t.WORD\t"
                   + ",".join(f"{cvt(x)}." for x in hp) + ",0")
    out.append("")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out))
    print(f"{args.out}: {len(songs)} songs, {len(phrases)} phrases, "
          f"{len(notes)} notes, {len(tones)} tones")


if __name__ == "__main__":
    main()
