#!/usr/bin/env python3
"""Compile sprite cells + entity frames/state tables into MACRO-11.

Usage:
    sprites_gen.py src/res/sprites --out build/data_sprites.mac [--force]

Input: cells.txt ('.' transparent, '#' ink, 'o' opaque black) and
entities.txt (frame blocks + state tables), see extract_res.py.

Output:
    SPR_CELLS: 256 cells x 8 glyph bytes (ink bits)
    SPR_MASKS: 256 cells x 8 mask bytes (1 = keep background)
    F_xxxx:    frame info blocks .BYTE w,h, cells...
    ST_BRUCE/ST_YAMO/ST_NINJA: per state .WORD frame, handler
Bit 0 = leftmost pixel (UKNC order).
"""
import argparse
import sys
from pathlib import Path


def parse_cells(path):
    cells = {}
    cur = None
    for raw in path.read_text().splitlines():
        line = raw.strip()
        is_row = len(line) == 8 and all(c in ".#o" for c in line)
        if not line or (line.startswith("#") and not is_row):
            continue
        if line.startswith("cell "):
            cur = int(line.split()[1], 16)
            cells[cur] = []
            continue
        if cur is None:
            continue
        if len(line) == 8 and all(c in ".#o" for c in line):
            g = sum(1 << i for i, c in enumerate(line) if c == "#")
            m = sum(1 << i for i, c in enumerate(line) if c == ".")
            cells[cur].append((g, m))
            if len(cells[cur]) == 8:
                cur = None
    return cells


def parse_entities(path):
    frames = {}
    entities = {}
    cur_frame = None
    cur_ent = None
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        parts = line.split()
        if parts[0] == "frame":
            name = parts[1]
            w = h = 0
            for p in parts[2:]:
                if p.startswith("w="):
                    w = int(p[2:])
                elif p.startswith("h="):
                    h = int(p[2:])
            cur_frame = name
            frames[name] = (w, h, [])
            cur_ent = None
            continue
        if parts[0] == "entity":
            cur_ent = parts[1]
            opts = dict(p.split("=") for p in parts[2:])
            entities[cur_ent] = {"tick": int(opts.get("tick", 4)),
                                 "color": int(opts.get("color", 7)),
                                 "states": {}}
            cur_frame = None
            continue
        if parts[0] == "state" and cur_ent:
            s = int(parts[1], 16)
            opts = dict(p.split("=") for p in parts[2:])
            entities[cur_ent]["states"][s] = (opts["frame"], opts["handler"])
            continue
        if cur_frame:
            frames[cur_frame][2].extend(int(p, 16) for p in parts)
    for name, (w, h, codes) in frames.items():
        if len(codes) != w * h:
            sys.exit(f"error: frame {name}: {len(codes)} cells for {w}x{h}")
    return frames, entities


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    if args.out.exists() and not args.force:
        sys.exit(f"error: {args.out} exists (use --force)")

    cells_r = parse_cells(args.input / "cells.txt")
    cells_l = parse_cells(args.input / "cells_l.txt")
    frames, entities = parse_entities(args.input / "entities.txt")

    out = ["; Generated by tools/sprites_gen.py from src/res/sprites/",
           "; -- do not edit; edit the .txt files and rebuild.", ""]
    # two facing sheets; masks pre-inverted (BIC clears bits set in src)
    for label, cells in (("SPR_CELLS", cells_r), ("SPR_CELLL", cells_l)):
        out.append(f"{label}:")
        for code in range(256):
            rows = cells.get(code, [(0, 0xFF)] * 8)
            out.append("\t.BYTE\t" + ",".join(f"{g:03o}" for g, _ in rows)
                       + f"\t; cell {code:02x}")
    for label, cells in (("SPR_MASKI", cells_r), ("SPR_MASKLI", cells_l)):
        out.append(f"{label}:")
        for code in range(256):
            rows = cells.get(code, [(0, 0xFF)] * 8)
            out.append("\t.BYTE\t" + ",".join(f"{m ^ 0xFF:03o}" for _, m in rows)
                       + f"\t; cell {code:02x}")
    out.append("")
    for name, (w, h, codes) in frames.items():
        out.append(f"{name.upper()}:\t.BYTE\t{w}.,{h}.,"
                   + ",".join(f"{c:03o}" for c in codes))
    out.append("\t.EVEN")
    out.append("")
    for ent, info in entities.items():
        out.append(f"ST_{ent.upper()}:")
        maxs = max(info["states"])
        for s in range(1, maxs + 1):
            frame, handler = info["states"].get(s, (list(frames)[0], "H_NOP"))
            out.append(f"\t.WORD\t{frame.upper()},{handler}\t; state {s:02x}")
        out.append("")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out))
    print(f"{args.out}: {len(frames)} frames, {len(entities)} entities")


if __name__ == "__main__":
    main()
