#!/usr/bin/env python3
"""Compile the UTF-8 game strings into MACRO-11 source.

Usage:
    text_gen.py src/res/text/strings.txt --out build/strings.mac [--force]

Input: one string per line, "label|text" (UTF-8; # starts a comment
line).  Output: "S_<LABEL>: .BYTE <encoded bytes>,0" in the game's text
encoding:

    32..95   ASCII (Latin lowercase is uppercased)
    96..127  Cyrillic А..Я in alphabet order (no Ё - it becomes Е;
             lowercase is uppercased)

The encoding matches the font table emitted by tools/font_gen.py.
An .EVEN follows every string so surrounding word-aligned code stays
aligned regardless of string length.
"""

import argparse
import sys
from pathlib import Path

CYR_ORDER = "АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"  # codes 96..127


def encode(text, where):
    out = []
    for ch in text:
        ch = ch.upper()
        if ch in ("Ё", "ё"):
            ch = "Е"
        if ch in CYR_ORDER:
            out.append(96 + CYR_ORDER.index(ch))
            continue
        code = ord(ch)
        if 32 <= code <= 95:
            out.append(code)
            continue
        sys.exit(f"error: {where}: no glyph for {ch!r}")
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    if args.out.exists() and not args.force:
        sys.exit(f"error: {args.out} exists (use --force)")
    out = ["; Generated by tools/text_gen.py from src/res/text/strings.txt",
           "; -- do not edit; edit the .txt and rebuild.",
           ""]
    count = 0
    for lineno, raw in enumerate(args.input.read_text().splitlines(), 1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if "|" not in raw:
            sys.exit(f"error: line {lineno}: expected 'label|text'")
        # keep the text exactly as written - trailing spaces are meaningful
        label, text = raw.split("|", 1)
        label = label.strip().upper()
        codes = encode(text, f"line {lineno} ({label})")
        codes.append(0)
        out.append(f"S_{label}:")
        out.append("\t.BYTE\t" + ",".join(str(c) + "." for c in codes)
                   + f"\t; \"{text}\"")
        out.append("\t.EVEN")
        count += 1
    out.append("")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out))
    print(f"{args.out}: {count} strings")


if __name__ == "__main__":
    main()
