#!/usr/bin/env python3
"""Compile background tiles into MACRO-11 source.

Usage:
    tiles_gen.py src/res/tiles/tiles.txt --out build/data_tiles.mac [--force]

Input (see extract_res.py): "tile HH combo=N ..." + 8 rows of '.'/'#'.
Output: TILE_GFX: 256 tiles x 8 words, pre-coloured for the UKNC:
low byte = plane 1 (cool/green), high byte = plane 2 (warm/red);
combo 1 -> plane 2, combo 2 -> plane 1, combo 3 -> both (white).
Bit 0 = leftmost pixel (UKNC plane order, reverse of the ZX).
"""
import argparse
import sys
from pathlib import Path


def revbits(b):
    r = 0
    for i in range(8):
        if b & (1 << i):
            r |= 1 << (7 - i)
    return r


def parse(path):
    tiles = {}
    cur = None
    rows = []
    for raw in path.read_text().splitlines():
        line = raw.strip()
        is_row = len(line) == 8 and all(c in ".#" for c in line)
        if not line or (line.startswith("#") and not is_row):
            continue
        if line.startswith("tile "):
            parts = line.split()
            code = int(parts[1], 16)
            combo = 1
            for p in parts[2:]:
                if p.startswith("combo="):
                    combo = int(p[6:])
            cur = code
            rows = []
            tiles[code] = (combo, rows)
            continue
        if cur is None or len(line) != 8 or any(c not in ".#" for c in line):
            sys.exit(f"error: bad line {raw!r}")
        rows.append(sum(1 << (7 - i) for i, c in enumerate(line) if c == "#"))
        if len(rows) == 8:
            cur = None
    return tiles


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    if args.out.exists() and not args.force:
        sys.exit(f"error: {args.out} exists (use --force)")
    tiles = parse(args.input)
    out = ["; Generated by tools/tiles_gen.py from src/res/tiles/tiles.txt",
           "; -- do not edit; edit the .txt and rebuild.", "",
           "TILE_GFX:"]
    for code in range(256):
        combo, rows = tiles.get(code, (1, [0] * 8))
        if len(rows) != 8:
            sys.exit(f"error: tile {code:02x}: {len(rows)} rows")
        words = []
        for g in rows:
            g = revbits(g)
            p1 = g if combo & 2 else 0
            p2 = g if combo & 1 else 0
            words.append(p1 | (p2 << 8))
        out.append("\t.WORD\t" + ",".join(f"{w:06o}" for w in words)
                   + f"\t; tile {code:02x}")
    out.append("")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out))
    print(f"{args.out}: {len(tiles)} tiles")


if __name__ == "__main__":
    main()
